name: Checkmarx Scan

on: [push,pull_request,workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkmarx AST Github Action
        uses: Checkmarx/ast-github-action@main
        with:
          base_uri: https://eu.ast.checkmarx.net/
          cx_tenant: cx_seg
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          additional_params: --scan-types "SAST" --sca-filter '!test,!swagger,!docs,!*_test.go,!**/webapp_service/**,!Dockerfile'
