name: Checkmarx Scan

on: [push,pull_request,workflow_dispatch]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2.0.14
      
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main
        with:
          base_uri: https://eu.ast.checkmarx.net/
          cx_tenant: cx_seg
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          additional_params: --scan-types "SAST, KICS"
